version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: guild_user
      POSTGRES_PASSWORD: guild_password
      POSTGRES_DB: guild_genesis
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: ["/app/app"]
    environment:
      RUST_LOG: debug
      RUST_BACKTRACE: 1
      PORT: 3001
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  indexer:
    build: ./indexer
    command: ["/app/app"]
    environment:
      RUST_LOG: debug
      RUST_BACKTRACE: 1
      PORT: 3002
    env_file:
      - .env
    ports:
      - "3002:3002"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        PUBLIC_WALLET_CONNECT_PROJECT_ID: ${PUBLIC_WALLET_CONNECT_PROJECT_ID}
        PUBLIC_API_URL: ${PUBLIC_API_URL}
        PUBLIC_BADGE_REGISTRY_ADDRESS: ${PUBLIC_BADGE_REGISTRY_ADDRESS}
        PUBLIC_EAS_CONTRACT_ADDRESS: ${PUBLIC_EAS_CONTRACT_ADDRESS}
        PUBLIC_ACTIVITY_TOKEN_ADDRESS: ${PUBLIC_ACTIVITY_TOKEN_ADDRESS}
        PUBLIC_SCHEMA_ID: ${PUBLIC_SCHEMA_ID}
    env_file:
      - .env
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pg_data:
