version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: guild_user
      POSTGRES_PASSWORD: guild_password
      POSTGRES_DB: guild_genesis
    ports:
      - "5433:5432"
    volumes:
      - pg_data_test:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      target: test
    command: ["cargo", "test"]
    environment:
      RUST_LOG: debug
      RUST_BACKTRACE: 1
      TEST_MODE: 1
      SKIP_MIGRATIONS: 1
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - postgres

volumes:
  pg_data_test:
