version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: guild_user
      POSTGRES_PASSWORD: guild_password
      POSTGRES_DB: guild_genesis
    ports:
      - "5433:5432"
    volumes:
      - pg_data_db:/var/lib/postgresql/data

volumes:
  pg_data_db:
