name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Run linter
        run: |
          cd frontend
          npm run lint

      - name: Run tests
        run: |
          cd frontend
          npm run test:run

      - name: Build frontend
        run: |
          cd frontend
          npm run build

  backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    env:
      TEST_MODE: "1"

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: guild_genesis_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            backend/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run migrations
        run: |
          cd backend
          cargo install sqlx-cli --no-default-features --features postgres,native-tls --locked
          cargo sqlx prepare
          sqlx migrate run
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/guild_genesis_test

      - name: Install dependencies
        run: |
          cd backend
          cargo build
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/guild_genesis_test

      - name: Run clippy
        run: |
          cd backend
          cargo clippy --all-targets --all-features -- -D warnings
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/guild_genesis_test

      - name: Run rustfmt
        run: |
          cd backend
          cargo fmt --all -- --check
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/guild_genesis_test

      - name: Run tests
        run: |
          cd backend
          cargo test --test integration_github_handle -- --test-threads=1
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/guild_genesis_test
          TEST_DATABASE_URL: postgres://postgres:postgres@localhost:5432/guild_genesis_test
          TEST_MODE: "1"

  smart-contracts:
    name: Smart Contracts Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
          cache: true

      - name: Cache Foundry
        uses: actions/cache@v3
        with:
          path: |
            ~/.foundry
            the-guild-smart-contracts/cache
            the-guild-smart-contracts/out
          key: ${{ runner.os }}-foundry-${{ hashFiles('the-guild-smart-contracts/foundry.lock') }}
          restore-keys: |
            ${{ runner.os }}-foundry-

      - name: Install OpenZeppelin
        run: |
          cd the-guild-smart-contracts
          forge install OpenZeppelin/openzeppelin-contracts

      - name: Build contracts
        run: |
          cd the-guild-smart-contracts
          forge build

      - name: Run tests
        run: |
          cd the-guild-smart-contracts
          forge test --verbosity

      - name: Run tests with gas reporting
        run: |
          cd the-guild-smart-contracts
          forge test --gas-report
